trigger:
- main

resources:
  repositories:
    - repository: templates
      type: github
      name: Rameshmamuduru/DevOps_Tools_flow
      endpoint: test
      ref: refs/heads/main

stages:
- stage: CI
  displayName: CI-Pipeline

  jobs:

  - template: templates/test.yaml@templates
    parameters:
      jobName: TestJob

  - template: templates/sonarqube_job.yaml@templates
    parameters:
      jobName: SonarJob
      projectKey: 'test'
      projectName: 'test'
      dependsOn: TestJob

  - template: templates/trivy_job.yaml@templates
    parameters:
      jobName: TrivyFSJob
      dependsOn: SonarJob

  - template: templates/docker_job.yaml@templates
    parameters:
      jobName: DockerJob
      repository: 'my_app'
      dependsOn: TrivyFSJob

  - template: templates/trivy_imagescan.yaml@templates
    parameters:
      jobName: TrivyImageJob
      IMAGE_NAME: 'my_app'
      dependsOn: DockerJob

  - template: templates/manifest_updater.yaml@templates
    parameters:
      jobName: ManifestUpdateJob
      dependsOn: TrivyImageJob
