apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-backend-{{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.app.name }}-{{ .Values.namespace }}
  template:
    metadata:
      labels:
        app: {{ .Values.app.name }}-{{ .Values.namespace }}
    spec:
      containers:
        - name: {{ .Release.Name }}-backend-{{ .Values.namespace }}
          image: {{ .Values.images.backend }}:{{ .Values.images.version }}
          ports:
            - containerPort: 5000
          env:
            - name: MYSQL_HOST
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: MYSQL_HOST
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: MYSQL_USER
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: MYSQL_PASSWORD
            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: MYSQL_DATABASE

---

apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-backend-{{ .Values.namespace }}
spec:
  selector:
    app: {{ .Values.app.name }}-{{ .Values.namespace }}
  ports:
    - port: 5000
      targetPort: 5000
  type: ClusterIP
