apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
stringData:
  mysql-root-password: root123
  mysql-user: appuser
  mysql-password: apppass
  mysql-database: devops_exam

---

apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
type: Opaque
stringData:
  MYSQL_HOST: mysql.default.svc.cluster.local
  MYSQL_USER: appuser
  MYSQL_PASSWORD: apppass
  MYSQL_DATABASE: devops_exam
