apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

nameSuffix: -dev

namePrefix: app1-

labels:
  - pairs:
      env: dev
    includeSelectors: true

replicas:
  - name: backend
    count: 2
  - name: mysql
    count: 2

patches:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: backend
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/env
        values:
          - name: LOG_LEVEL
            value: debug


    
