parameters:
  vmImage: 'ubuntu-latest'
  repository: ''

jobs:
- job: docker-job
  pool:
    vmImage: ${{ parameters.vmImage }}

  steps:
  - checkout: self
  - - task: Docker@2
      inputs:
        containerRegistry: 'test-docker'
        repository: '${{ parameters.repository }}'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
