apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

nameSuffix: -prod

namePrifix: -app1

labels:
  - pairs:
      env: prod
      includeSeclectors: true

replicas:
  - name: Nginx-Deploy
    count: 4