apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

nameSuffix: -stage

namePrefix: app1-

labels:
  - pairs:
      env: stage
    includeSelectors: true

replicas:
  - name: backend
    count: 3
  - name: mysql
    count: 2

patchesStrategicMerge:
  - patch_deployment.yml