name: Build Docker image, push, and update Helm for EKS Deployment

on:
  push:
    branches:
      - master
  workflow_dispatch:
    inputs:
      ENVIRONMENT:
        description: 'Selection of Deployment Environment is Mandatory'
        required: true
        default: 'Dev'
        type: choice
        options:
          - Dev
          - Stage
          - Prod

env:
  IMAGE_NAME: ramesh0621/backend-1
  IMAGE_TAG: ${{ github.run_number }}

jobs:
  setting_up_environment:
    runs-on: ubuntu-latest
    steps:
      - name: Print Deployment Environment
        run: |
          echo "Deployment To Environment: ${{ github.event.inputs.ENVIRONMENT }}"
